[package]
name = "hexforge"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
hexforge-core = { path = "../crates/hexforge-core" }
hexforge-ops = { path = "../crates/hexforge-ops" }
tauri = { version = "2", features = [] }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "fs"] }
thiserror = { workspace = true }
memmap2 = "0.9"
base64 = "0.22"
parking_lot = "0.12"

[features]
custom-protocol = ["tauri/custom-protocol"]
